- name: Install local machine
  hosts: 127.0.0.1
  connection: local
  vars:
    lsb_name: focal
    user: jelle
    database_user: jelle
    database_password: jelle
    slack_version: 4.10.0
    virtualbox_version: 6.1
  become: yes

  tasks:
    - import_tasks: tasks/common.yml
    - name: Install core packages
      apt:
        state: present
        pkg:
          - lsb-release
          - apt-transport-https
          - ca-certificates
          - curl
          - wget
          - software-properties-common
          - gnupg2
          - unzip
          - python3-pip
    - import_tasks: tasks/enpass.yml
    - import_tasks: tasks/chrome.yml
    - import_tasks: tasks/slack.yml
    - import_tasks: tasks/vscode.yml
    - import_tasks: tasks/php.yml
    - import_tasks: tasks/composer.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/mysql.yml
    - import_tasks: tasks/redis.yml
    - import_tasks: tasks/cron.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/virtualbox.yml
    - import_tasks: tasks/vagrant.yml
