- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Check if .zshrc exists
  stat:
    path: /home/{{ user }}/.zshrc
  register: stat_rc_result

- name: Check if .oh-my-zsh exists
  stat:
    path: /home/{{ user }}/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: /home/{{ user }}/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists

- name: Creating new /home/{{ user }}/.zshrc
  copy:
    src: /home/{{ user }}/.oh-my-zsh/templates/zshrc.zsh-template
    dest: /home/{{ user }}/.zshrc
  when: not stat_rc_result.stat.exists

- name: change user shell to zsh
  user:
    name: "{{ user }}"
    shell: /bin/zsh
