- name: Install zsh
  tags: zsh
  apt:
    name: zsh
    state: present

- name: Check if .zshrc exists
  become: yes
  become_user: "{{ user }}"
  tags: zsh
  stat:
    path: ~/.zshrc
  register: stat_rc_result

- name: Check if .oh-my-zsh exists
  become: yes
  become_user: "{{ user }}"
  tags: zsh
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Cloning oh-my-zsh
  become: yes
  become_user: "{{ user }}"
  tags: zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists

- name: Creating new ~/.zshrc
  become: yes
  become_user: "{{ user }}"
  tags: zsh
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
  when: not stat_rc_result.stat.exists

- name: change user shell to zsh
  tags: zsh
  user:
    name: "{{ user }}"
    shell: /bin/zsh
